### ISSUE TITLE
 mIndicatorView.setPageIndicators(5);

### ISSUE THREAD

**Issue by sujito2o** [Kshitij-Jain/IndicatorView#1]
Only working inside onCreateView . I am trying to add dynamically  inside OnSuccess callback of my api .

**Comment by KshitijDroid** [comment]
Please call mIndicatorView.requestLayout() after dynamically setting Page Indicators.

**Comment by sujito2o** [comment]
Thanks for the reply . It worked .

**Comment by KshitijDroid** [comment]
:)
